### PR TITLE
Ensures that vagrant plugin depdendencies are installed

### PR DESCRIPTION
**Pull request by miroswan**
Installs vagrant plugins for the user.

### CODE REVIEW

**Comment by ankanm** [comment]
LGTM. 
It appears it's not possible to continue on after installing the plugins. That would be ideal.

**Comment by miroswan** [comment]
Yeah. I actually looked into it. There is a context that is setup prior to plugin installation so there is an object somewhere that doesn't get updated. There is a long thread about this here:

https://github.com/mitchellh/vagrant/issues/1874

**Comment by ankanm** [comment]
Yes. Saw that while searching.
Can we add a prompt before installing plugin? It's a good idea to ask before changing the host.

**Comment by miroswan** [comment]
Sure. Sounds good.

**Pull request closed without merging**
