### PR TITLE
Ankan/roger 985 version affinity roger 984 http prefix substrings

### PR DESCRIPTION
**Pull request by ankanm**
* ROGER-985 - [LB] Update LB to support multiple versions of an http app (with version affinity)
* ROGER-984 - [LB] Update LB to better support HTTP_PREFIX substrings

**What?**
`1` Make order of first deployment irrelevant when deploying apps to paths like `http://example.com/foo` and `http://example.com/foo/bar`. Currently for this to work `/foo/bar` needs to be deployed first followed by `/foo` (when deployed for the first time or after a destroy.)
`2` Support for having the same http endpoint for multiple apps (to allow making multiple versions available at the same endpoint.)
`3` Support for version affinity that sends requests from existing clients to the same backend even if new requests go to a new backend on the same endpoint. For example - 
 * say there's an app `mycoolapp-v1` that is deployed at `http://example.com/mycoolapp`.
 * a new version `mycoolapp-v2` can now also be deployed at `http://example.com/mycoolapp`.
 * New clients (sessions) will now be routed to v2 while existing clients (that are already connected to v1) will continue to be routed to v1.
 * If v1 is then shut down, all clients will get routed to v2. 
 * Notes 
    * There can also be more such instances say v3, v4, etc. These can be *any* string. New sessions will get routed to the latest (last created) app.
    * For the above to work, an `ENABLE_VERSION_AFFINITY` env var needs to be set to a string (e.g. `v1` or `v2`) that can be used to differentiate the instances.
    * From a marathon standpoint, these versions are different apps (i.e., have different app ids.) So, upgrading will require manually scaling down (or stopping) old versions when required.

**How? (code changes)**
* Switched to new bamboo version (https://github.com/seomoz/roger-bamboo/pull/15) that has the ability to store/prioritize haproxy acls and backend rules during config generation.
* Completely revamped the acl/backend declaration section to do the following - 
  * Instead of writing the `acl` and the corresponding `use_backend` rule immediately
    * store acls in a set thus ensuring that there is only 1 acl entry when there are multiple apps with the same acl entries (e.g., http prefix).
    * store backends in a map (along with condition as key) with overwriting to ensure that if there are multiple apps with the same condition the last one wins.
    * write all acls in a section first and then the use_backend rules in a later section.
  * with version affinity enabled create additional acl entries to check cookie, and also add a version hash cookie in the backend.
  * write backends in descending order of conditions (acls) - this is to support `1` above (ensure that `/foo/bar` rule is always before `/foo`).
* Changed the acl and backend naming conventions to better support all of the above (e.g. use `HTTP_PREFIX` when available, use version hash to differentiate backends and additional acl rules, etc.)

### CODE REVIEW

**Comment by wescarr** [comment]
@ankanm Can you clarify what you mean by existing clients will continue to get routed to their current version? Is that based on cookie?

Also what about support for automatically killing old versions when they are no longer servicing any requests?

**Comment by ankanm** [comment]
@wescarr - Yes, that routing is based on a cookie called `VERSIONID` which is a hash from the the app id and the `ENABLE_VERSION_AFFINITY` env var value.

Right now, the old versions need to be killed manually. We could add some support for that in the future.

**Comment by wescarr** [comment]
How would one know when it's safe to manually down scale?

**Comment by ankanm** [comment]
This implementation only allows you to ensure that the same client doesn't end up switching between 2 (or more) versions. At any point you could stop the old version(s), and all new requests would end up going to the latest version.
If you're worried about ensuring that all requests are processed and only then the old backend stops, this PR is not doing that. (There is also a docker related issue - https://issues.apache.org/jira/browse/MESOS-4279.)
However, what it does is that it allows you to start a new task at the same end point and get all new requests to this new task, eventually allowing you to stop your old task (perhaps automated some way in the future.)
For most stateless apps, the current way of using just 1 marathon task may be sufficient and there is no need for using version affinity.

**Comment by ankanm** [comment]
@wescarr - Also, if you really need to, you would be able to monitor connections per app to know when it drops to zero (that's something we could leverage to automate this in the future.)

**Comment by cwhitten** [comment]
@ankanm If client1 has a v1 cookie after all instances of v1 are scaled down, and there are versions v2 and v3 available to the client who now has a "stale" v1 cookie, which version gets pinned to the client?

**Comment by ankanm** [comment]
@cwhitten - Yes, the last created one (typically v3).

**Comment by cwhitten** [comment]
@ankanm good stuff, this will be really useful.

Eventually, we would like to supply a distribution percentage along with the new version that we can dynamically change (possibly in marathon?). Say we deploy `v2` and would like 10% of traffic assigned to it and 90% of traffic assigned to `v1`, gradually increasing the traffic into `v2` and out of `v1`. This would obviously require some changes to which version gets pinned to a client with a dead session (or not session at all)

**Comment by ankanm** [comment]
@cwhitten - Great! Sounds good.

**Pull request merged**
